name: sqlite_inspector
description: Dev-only HTTP inspector for on-device SQLite (debug)
version: 0.0.1

repository: https://github.com/macss-dev/sqlite_inspector
homepage: https://github.com/macss-dev/sqlite_inspector
issue_tracker: https://github.com/macss-dev/sqlite_inspector/issues
documentation: https://github.com/macss-dev/sqlite_inspector/latest

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  sqlite3: ^2.9.3
  sqlite3_flutter_libs: ^0.5.40

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

topics:
  - sqlite
  - debug
  - developer-tools
  - macss